rec1 = "TTGAAGGGAATTTGCGAATATTTGGGGGAAAATTTAAAATTTACAGTTTATTTAAATTTGAAAAAAAAAT
CAAATAAACAATTTATCAACACAATTTTGAATTTTATTCTGAAAAATGTCAACTTTTGCCCAAAAAAAAT
AGTGAAAATCATAAATCGCGGCGAGTCCTGCGGAATATTTTACGCCATGTGCCTTTAGTACCGTAACGCT
TCTCTTCATTTTCGAAATTCTAAATATTTTCCGCTTTTTTTTCGTCAAAAATGCCCGGAAATGATGATAT
TGTAATGTTATCAGGTGATTTTAGCCAGATTTTTAGCAGGTTTTAGCAGAAAAACGTTTTCAGACGAGAT
AGTAGCAGATCTTCGCCGATTTATCGCCAGCCGGCCAGTTATCCAGTTCGATCGGCGACCAGGATACGTT
CCGACGCCGTGGAGAAATTGCTGGAAAGTGGGAAAAGCTGACAATGAGAAAAGAGCAAAAAAAAGCAAAA
AAAATCGATTTTTTCAGGAAATAATCGAAATTTGGTCGGATGATGATTCAGAGGATGACGACGGCGACGT
GATTACAGGCTCTCAAGAAGCCCAGCTGAAAAGGCTGAATAATGAAGAAGCTGGGAGCTCATCGTGCCGA
AAATCACCAGAAACTGCAAAATCTACGCCAAAAGTCAGAAAACCTGTCGAAATTCCAAAGATTAGCTCAG
AAAAATTGCCGGAAACTGCGAATTCTACTGAAAATCAAGACGCCCCCGCTACTGAGCAGACAATTCTGAA
CAATAGAGCAGCTGGAAGCTCCCCGAGCCCAAAATCACCGAGATTTGCAGAAAAACCGTCAGAAATTGCG
AAATCTACGCCGAAAATCAGAAAACTTGTCAAAATTTCGAAGATTTGCTCAGAAAAATTGCCGAAAACTG
CGAATTCTACTGAAAATCAAGACGCCCCCGCTACTGAGCAGACAATGCTGAACAATAGAGCAGCTGGGAG
CTCCCCGAGCCGAAAATCACCGGGATTTGCAGAAAAACCGTCAGAATTTGCGAAATCTACGCCGAAAATC
AGAAAACTTGTCGAAATTTCGAAGATTTGCTCAGAAAAATTGCCGGAAACTGCGAATTCTACTGAAAAAA
TTGCGTTGGACTTCAAGAAACTTGTCGAAATTTCAAAGATTGCTCTAAAAGCTGAAATCCCAGAACCTGA
GCGAAAAAGGCTCAGAAAATCACCGAGATTGGCGGGATCAACGAAAATTCCGCTGATTAGACCTGAAAAA
CAGTCTGAAACTGCGAAATCTACGCCGAGTAAAAGAAAAATCACGGAGTTCTGGCCTTCCTCATTGAATT
TTTCGCGCTCCATTGACAATCGCCTGCCGGACAACGCGTGGGAAAGTCGTGTACTCCACACGGACAAATC
ACATTTAGTTTTACAACTAAAATCGAGCCGCGACGCGACACGCAACGCGCCGTAAATCTACCCCAGATAT
GGCCTGGCCTAGTTCGGCAAAAACTCTTCCATTTCAATTCTTTGAGGGAAACCAGAAATCCGTGTTAAAA
ATTCAGAAAATTCAAGTCAAAACTCGTGTTTTTTTTTCAGAAAACTTCAAGGAATCAAAGTCACTGAACG
CACAATGCAAGCTGGAAATGCAGCTCGCCAGATTCAAAGCGCTTCGGGTAAAAAAAAAGAAATTTCTCGA
AATTCCAAAAAATTCAAATCTTTCAGCTCTCAAAACCTTCCAAAAACCACCGGAGCAGCCGACAATGTGC
AGCAATCTCCGAAAAAAAGTCGAAAATTATGATGAATTCCTGGGCGGAGGACTCGATTTTCGAAAAATAA
TCTTAATCTTGATGCATCTTTTACTATTTTTGTAATATTTCCCCTCATGTTCCATTTTTTATTCTTCCAC
AACAGTTTTCTTTTCCACGTGATGCGCCTTTAATTAATTAGGACTAGTTTTGCTGTGTTCTCACTTGTTT
TCACTCGATTTTCCGTTGTCTGTTCGTTTTTTTTTTGCCTCAAAATTTGCTATTTAGCGACCAATGACCG
AATAAAGTGGTTTTTAAAATAGAAA"

library(data.table)
rec1 = paste(unlist(tstrsplit(rec1, '\n')), collapse="")

primerF = "GCAGGTTTTAGCAGAAAAACG"
primerR = "CGTCGGAACGTATCCTGGT"

deletion = "GGCCGGCT"

oppositeStrand = function(seq){
  seq = unlist(strsplit(seq, ''))
  wA = which(seq == 'A')
  wT = which(seq == 'T')
  wC = which(seq == 'C')
  wG = which(seq == 'G')
  
  seq[wA] = 'T'
  seq[wT] = 'A'
  seq[wC] = 'G'
  seq[wG] = 'C'
  
  seq = seq[length(seq):1]
  paste(seq, collapse="")
  
  
}

primerR  = oppositeStrand(primerR)

#Wild type PCR product
ampli_wt = strsplit(rec1, primerF)[[1]][2]
ampli_wt = strsplit(ampli_wt, primerR)[[1]][1]

#Mutant PCR product
ampli_mut = paste(unlist(strsplit(ampli, oppositeStrand(deletion))), collapse="")


paste(unlist(strsplit(ampli, oppositeStrand(deletion))[[1]]), collapse="")



length(unlist(strsplit(ampli_wt, "")[[1]])) #Length PCR product wt
length(unlist(strsplit(ampli_mut, "")[[1]])) #Length PCR product mut


